Do not link the site-packages/__pycache__ directory
Otherwise, "hit develop" builds with python3 cannot use pip since it
wants to put new files into site-packages/__pycache__

$ ./default/bin/pip3 install ipython glob2 pyyaml ld jinja2
...
PermissionError: [Errno 13] Permission denied: '/home/.../site-packages/__pycache__/decorator.cpython-35.pyc'